= 8-115 npx Create React App Generation

`npx create-react-app client`

https://create-react-app.dev/docs/getting-started#quick-start[Official docs on CRA usage with npx are available here].

== Run Docker Compose

```
docker-compose up
# OR build image and start container
docker-compose up --build
```
== S14 - A Multi-Container App with Kubernetes

==== L209 - A Quick Checkpoint
```
# Run from inside of complex folder
docker-compose up --build
```

==== L213 - Applying Multiple Files with Kubectl
```
# Check current deployments/services
kubectl get deployments
kubectl get services

# Delete previous deployment/services
kubectl delete deployment client-deployment
kubectl delete service client-node-port

# Apply all the config files from specified directory
kubectl apply -f k8s

# Check created pods/services
kubectl get pods
kubectl get services
```

==== L227 - Persistent Volume Access Modes
```
kubectl get storageclass
kubectl describe storageclass
```

==== L230 - Applying PVC
```
# List persistent values
kubectl get pv
# List persistent volumes claims
kubectl get pvc
```

==== L233 - Creating an Encoded Secret
```
kubectl create secret generic <secret_name> --from-literal key=value

# Example for PGPASSWORD
kubectl create secret generic pgpassword --from-literal PGPASSWORD=12345asdf

# Verify secret object
kubectl get secrets
```
==== L236 - Environment Variables as Strings
```
# Apply all the config files from specified directory
kubectl apply -f k8s
```

== S15 - Handling Taffic with Ingress Controllers

==== L244 - Setting Up Ingres Locally with Minikube
https://kubernetes.github.io/ingress-nginx/deploy/#provider-specific-steps[Provider Specific Steps]

```
minikube addons enable ingress
```
==== L249 - "Indexes I Have Seen" is Empty
```
# Run inside of the server directory
docker build -t zakdim/multi-server .
docker push zakdim/multi-server

kubectl delete -f k8s/
kubectl apply -f k8s/
```

==== L250 - The Minikube Dashboard

```
minikube dashboard
```
== S16

==== L266 - Ruby Version Fix

```
# Use the v2.4 version of Ruby instead of v2.3
docker run -it -v $(pwd):/app ruby:2.4 sh
```

==== L267 - Running Travis CLI in a Container

Use docker container with Ruby to encrypt service-account.json file.

```
# Create and start docker container with ruby
docker run -it -v $(pwd):/app ruby:2.4 sh

# Install Travic CLI inside of container
gem install travis --no-rdoc --no-ri
# Or
gem install travis

travis
```

==== L268 - Fixes for Travis "iv undefined" or"repository not known"
```
# Pass the --com flags to both these commands below:

travis login --com
travis encrypt-file service.json -r USERNAME/REPO --com
```

==== L269 - Encrypting a Service Account File
```
travis login

# Copy json file into the 'volumed' directory
# so we can use it in the container
travis encrypt-file service-account.json -r zakdim/multi-k8s
```

==== L271 - Fix for Failing Travis Builds

Make sure to change this script:

```
script:
  - docker run USERNAME/docker-react npm run test -- --coverage
To use the CI flag and remove coverage:

script:
  - docker run -e CI=true USERNAME/docker-react npm run test
```

==== L277 - Configuring the GCloud CLI on Cloud Console

Run in GCloud Console:

```
gcloud config set project multi-k8s-278620

# Set compute zone
gcloud config set compute/zone us-central1-c	

# Get credentials
gcloud container clusters get-credentials multi-cluster

```

==== L277 - Create a Secret on Google Cloud

```
kubectl create secret generic pgpassword --from-literal PGPASSWORD=mypgpassword123
```

==== L279 - Helm V3 Update

1. Install Helm v3:

```
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
chmod 700 get_helm.sh
./get_helm.sh
```

2. Skip the commands run in the following lectures:

Helm Setup, Kubernetes Security with RBAC, Assigning Tiller a Service Account and Ingress-Nginx with Helm. You should still watch these lectures and they contain otherwise useful info.

3. Install Ingress-Nginx:

```
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
helm install my-nginx stable/nginx-ingress --set rbac.create=true 

# OUTPUT:
The nginx-ingress controller has been installed.
It may take a few minutes for the LoadBalancer IP to be available.
You can watch the status by running 'kubectl --namespace default get services -o wide -w my-nginx-nginx-ingress-controller'
```
